import { Button, Closing, Eyebrow, Photo, TextLink } from '@/components/ui';
import { Explorer } from '@/components/explorer';
export default function Home(){return <>
<section className="home-hero wrap"><div className="hero-kicker"><Eyebrow>Orange County. Since 1995.</Eyebrow><span className="small-label">Youth leaders. Strong families. Thriving communities.</span></div><div className="hero-grid"><div className="hero-copy"><h1>BRIGHTER<br/>FUTURES.<br/><span>TOGETHER.</span></h1><p>Every young person deserves the chance to thrive.<br className="desktop-break"/> We build the skills, relationships, and healthier communities that help make it happen.</p><div className="hero-actions"><Button href="/programs">Discover our work</Button><TextLink href="/get-involved">Be part of it</TextLink></div></div><div className="hero-visual"><div className="hero-photo-frame"><Photo src="mentoring.jpg" alt="A group gathered outdoors in a photograph from America On Track’s program archive" priority/><div className="photo-corner" aria-hidden="true">↗</div></div><div className="hero-stamp"><span>ONE CONNECTION.</span><b>ENDLESS<br/>POSSIBILITY.</b><span aria-hidden="true">✳</span></div><div className="hero-caption"><span>Real connections. Lasting possibilities.</span><span>01 / AOT</span></div></div></div><div className="hero-bottom"><span>A brighter future is a shared achievement.</span><a href="#connections">See how it connects <span aria-hidden="true">↓</span></a></div></section>
<section className="intro wrap"><p className="eyebrow">A local commitment.<br/>A lifelong difference.</p><div><h2>Potential is everywhere.<br/><span>Opportunity should be, too.</span></h2><p>For more than three decades, America On Track has brought people together to open doors for Orange County’s children and families. Through leadership, mentoring, health education, and community action, we help possibility become a path forward.</p><TextLink href="/about">Meet America On Track</TextLink></div></section>
<Explorer/>
<section className="feature wrap"><div className="feature-image"><Photo src="leaders.jpg" alt="Emerging Leaders scholarship recipients with co-founder Terry Thompson"/><span className="image-tag">In focus / Emerging Leaders</span></div><div className="feature-copy"><Eyebrow>Today’s students. Tomorrow’s leaders.</Eyebrow><h2>More than finding a voice.<br/><span>Learning to use it.</span></h2><p>Public speaking. STEM exploration. Community service. Our Emerging Leaders program gives students in grades 4–12 a place to build confidence—and put it into action.</p><TextLink href="/programs/emerging-leaders">Explore Emerging Leaders</TextLink><div className="feature-footnote"><b>GRADES 4–12</b><span>After school.<br/>Beyond expectations.</span></div></div></section>
<section className="impact-preview"><div className="wrap"><div className="impact-heading"><Eyebrow>Built on commitment. Backed by experience.</Eyebrow><h2>Small beginnings.<br/>Lasting change.</h2><TextLink href="/impact">Explore our impact</TextLink></div><div className="impact-facts"><article><span className="big-number">1995</span><h3>A commitment that continues.</h3><p>Founded by Terry Thompson and Claire Braeburn to respond to the needs of Orange County children and families.</p></article><article><span className="big-number">5,597</span><h3>Moments of learning & connection.</h3><p>Classes, presentations, trainings, and events reported in 2019 across five core programs.</p><span className="data-label">Historical snapshot · 2019</span></article><article className="impact-quote"><span className="quote-mark" aria-hidden="true">“</span><blockquote>I definitely want to pay it forward.</blockquote><p>A former mentee who became a mentor<br/><span className="data-label">From the published results archive</span></p></article></div></div></section>
<section className="golf-strip wrap"><div className="date-block"><span>OCT</span><strong>26</strong><span>2026</span></div><div><Eyebrow>A good day out. A greater purpose.</Eyebrow><h2>Kids On Track Golf Tournament</h2><p>The Huntington Club · Huntington Beach<br/>Supporting youth leadership development.</p></div><Button href="/events/golf" secondary>Join us on the course</Button></section>
<section className="people-strip"><Photo src="camp.jpg" alt="America On Track participants and volunteers at a camp gathering" sizes="100vw"/><div className="people-strip-label"><span>Many people.</span><strong>ONE SHARED FUTURE.</strong></div></section>
<Closing/>
</>}
