'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ConnectionMap } from './connection-map';
import { Photo, TextLink } from './ui';
import { programs } from '@/lib/content';
const layers=[{name:'Young people',word:'A voice.',text:'Confidence. Connection. The chance to lead. Start with the programs that help young people see what’s possible.',image:'stem.jpg',alt:'Emerging Leaders collaborating on a STEM project',keys:['emerging-leaders','brighter-futures','drug-use-prevention']},{name:'Families',word:'A circle.',text:'Strong relationships and practical support reach beyond one child. Discover learning and encouragement for the whole family.',image:'mentor.jpg',alt:'An America On Track mentor and mentee at an event',keys:['brighter-futures','nutrition']},{name:'Communities',word:'A future.',text:'Healthier schools and public spaces help everyone move forward. Connect with the work that changes the places we share.',image:'park.jpg',alt:'A public park pictured in America On Track’s community health work',keys:['fitness','nutrition','tobacco-free-communities']}];
export function Explorer(){const [active,setActive]=useState(0);const layer=layers[active];return <section className="explorer" id="connections"><div className="wrap"><div className="section-top"><p className="eyebrow">The power of connection</p><span className="small-label">One mission. Wider possibilities.</span></div><h2>It starts with one person.<br/><span>It reaches a whole community.</span></h2><div className="connection-tabs" role="tablist" aria-label="Explore who our work supports">{layers.map((l,i)=><button key={l.name} id={`tab-${i}`} role="tab" aria-selected={active===i} aria-controls="connection-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowLeft')n=(i+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();setActive(n);document.getElementById(`tab-${n}`)?.focus()}}><span className="node">0{i+1}</span><span>{l.name}</span><span className="tab-arrow" aria-hidden="true">↗</span></button>)}</div><div id="connection-panel" className="connection-panel" role="tabpanel" aria-labelledby={`tab-${active}`} tabIndex={0}><div className="connection-copy" key={layer.name}><h3>{layer.word}</h3><p>{layer.text}</p><div className="connection-links">{layer.keys.map(slug=>{const p=programs.find(x=>x.slug===slug)!;return <TextLink key={slug} href={`/programs/${slug}`}>{p.name}</TextLink>})}</div></div><Photo src={layer.image} alt={layer.alt}/><ConnectionMap level={active}/></div><noscript><p>Explore all six programs and their audiences on our <Link href="/programs">programs page</Link>.</p></noscript></div></section>}
export function ProgramFilter(){const [filter,setFilter]=useState('all');const filters=[['all','Everyone'],['youth','Young people'],['families','Families'],['schools','Schools'],['community','Community partners']];return <div><div className="filter-bar" aria-label="Filter programs by audience">{filters.map(([key,name])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{name}</button>)}</div><p className="filter-count" aria-live="polite">{programs.filter(p=>filter==='all'||p.areas.includes(filter)).length} programs · Choose a program to explore</p><div className="program-list">{programs.filter(p=>filter==='all'||p.areas.includes(filter)).map(p=><a key={p.slug} className="program-row" href={`/programs/${p.slug}`}><span className="program-number">{p.number}</span><div><h2>{p.name}</h2><p>{p.short}</p></div><span className="program-audience">{p.audience}</span><span className="row-arrow" aria-hidden="true">↗</span></a>)}</div></div>}
